# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/48576/Desktop/STUDIA/6 sem/SR/lab4/arithmetic/arithmetic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
# IP: The module: 'mult_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/48576/Desktop/STUDIA/6 sem/SR/lab4/arithmetic/arithmetic.gen/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/48576/Desktop/STUDIA/6 sem/SR/lab4/arithmetic/arithmetic.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
# IP: The module: 'mult_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/48576/Desktop/STUDIA/6 sem/SR/lab4/arithmetic/arithmetic.gen/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
